export { default } from "./src/wallet-manager-selendra.js";
export { SELENDRA_MAINNET, SELENDRA_TESTNET } from "./src/chains.js";
export type { default as WalletAccountEvm } from "@tetherto/wdk-wallet-evm";
export type { default as WalletAccountReadOnlyEvm } from "@tetherto/wdk-wallet-evm";
export type TypedDataDomain = import("ethers").TypedDataDomain;
export type TypedDataField = import("ethers").TypedDataField;
export type AuthorizationRequest = import("ethers").AuthorizationRequest;
export type Authorization = import("ethers").Authorization;
export type AuthorizationLike = import("ethers").AuthorizationLike;
export type EvmTransactionReceipt = import("ethers").TransactionReceipt;
export type FeeRates = import("@tetherto/wdk-wallet").FeeRates;
export type KeyPair = import("@tetherto/wdk-wallet").KeyPair;
export type TransactionResult = import("@tetherto/wdk-wallet").TransactionResult;
export type TransferResult = import("@tetherto/wdk-wallet").TransferResult;
export type TypedData = import("@tetherto/wdk-wallet-evm").TypedData;
export type DelegationInfo = import("@tetherto/wdk-wallet-evm").DelegationInfo;
export type EvmTransaction = import("@tetherto/wdk-wallet-evm").EvmTransaction;
export type EvmTransferOptions = import("@tetherto/wdk-wallet-evm").EvmTransferOptions;
export type EvmWalletConfig = import("@tetherto/wdk-wallet-evm").EvmWalletConfig;
export type ApproveOptions = import("@tetherto/wdk-wallet-evm").ApproveOptions;
